name: Deploy Angular App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on main branch
        run: echo github.ref
        if: endsWith( github.ref, 'main' ) != true
        run: exit -1
      - run: echo foo
