name: Deploy Angular App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on main branch
        run: echo github.ref
      - run: echo foo
